In [17]:
# EXPERIMENT - 11
# Create NumPy arrays with different methods (lists, zeros, ones, arange).

import numpy as np

# Creating array from list
dataList = [1, 2, 3, 4, 5]
arrFromList = np.array(dataList)
print("Array from list:", arrFromList)

# Creating array filled with zeros
zeroArr = np.zeros(5)
print("Zero array:", zeroArr)

# Creating 2D array filled with ones
oneArr = np.ones((3, 4))
print("Ones Array:\n", oneArr)

# Creating array from range 0 to 10, even numbers only
rangeArr = np.arange(0, 11, 2)
print("Array from range:", rangeArr)

Array from list: [1 2 3 4 5]
Zero array: [0. 0. 0. 0. 0.]
Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array from range: [ 0  2  4  6  8 10]


In [12]:
# Perform mathematical operations on NumPy arrays 
# (addition, subtraction, multiplication, division).

arr1 = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])
arr2 = np.array([6, 7, 8, 9, -1])

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

print("\nSum of arrays:\n", np.add(arr1, arr2))
print("\nDifference of arrays:\n", np.subtract(arr1, arr2))
print("\nProduct of arrays:\n", np.multiply(arr1, arr2))
print("\nDivision of arrays:\n", np.divide(arr1, arr2))

Array 1:
 [[1 2 3 4 5]
 [5 4 3 2 1]]
Array 2:
 [ 6  7  8  9 -1]

Sum of arrays:
 [[ 7  9 11 13  4]
 [11 11 11 11  0]]

Difference of arrays:
 [[-5 -5 -5 -5  6]
 [-1 -3 -5 -7  2]]

Product of arrays:
 [[ 6 14 24 36 -5]
 [30 28 24 18 -1]]

Division of arrays:
 [[ 0.16666667  0.28571429  0.375       0.44444444 -5.        ]
 [ 0.83333333  0.57142857  0.375       0.22222222 -1.        ]]


In [11]:
# Practice indexing and slicing NumPy arrays.

# Declaring a 2D array
array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])

print("Array: ")
print(array)

# Indexing
print("\nINDEXING:")
print("First Element:", array[0, 0])
print("Last Element of first row:", array[0, -1])
print("First Element of second row:", array[1, 0])
print("Last Element of second row:", array[1, -1])

# Slicing
print("\nSLICING:")
print("Middle 3 elements of first row:", array[0, 1:4])
print("Last 3 elements of second row:", array[1, -3:])
print("Odd positioned elements of first row:", array[0, ::2])
print("Middle 3 elements of both rows:\n", array[0:2, 1:4])

Array: 
[[1 2 3 4 5]
 [6 7 8 9 0]]

INDEXING:
First Element: 1
Last Element of first row: 5
First Element of second row: 6
Last Element of second row: 0

SLICING:
Middle 3 elements of first row: [2 3 4]
Last 3 elements of second row: [8 9 0]
Odd positioned elements of first row: [1 3 5]
Middle 3 elements of both rows:
 [[2 3 4]
 [7 8 9]]


In [19]:
# Use NumPy functions for basic statistical analysis like mean, median and mode.

from scipy import stats

arr = [99, 86, 87, 88, 111, 86, 103, 87, 94, 78, 77, 85, 86]
print("Array:", arr)

# Mean
mean = np.mean(arr)
print("Mean:", mean)

# Median 
median = np.median(arr)
print("Median:", median)

# Mode
mode = stats.mode(arr)
print("Mode:", mode)

Array: [99, 86, 87, 88, 111, 86, 103, 87, 94, 78, 77, 85, 86]
Mean: 89.76923076923077
Median: 87.0
Mode: ModeResult(mode=86, count=3)


In [26]:
# Experiment with reshaping and transposing NumPy arrays

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("Array:\n", arr)

# Transpose of array
arrTranspose = np.transpose(arr)
print("\nTransposed Array:\n", arrTranspose)

# Reshaping - Flattening
flatArr = arr.reshape(-1)
print("\nFlattened Array:", flatArr)

# Reshaping to 2 x 6 array
reshapedArr = arr.reshape(2, 6)
print("\nReshaped Array:\n", reshapedArr)

# Reshaping into 3D array, outermost level has 2 arrays, each of
# which contains 3 arrays with 2 elements each
reshapedArr = arr.reshape(2, 3, 2)
print("\nReshaped Array:\n", reshapedArr)

Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Transposed Array:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]

Flattened Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Reshaped Array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
