In [1]:
# 1. Write a Python function to reverse a list.

def reverse(userList):
    return userList[::-1]

userList = [1, 2, 3, 4, 5]
resList = reverse(userList)
print(resList)

[5, 4, 3, 2, 1]


In [2]:
# 2. Create a NumPy array filled with zeros of shape (3, 3).

import numpy as np
arr = np.zeros((3, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# 3. Write a function to check if a given number is prime or not.

def checkPrime(num):
    if (num < 2):
        return False
    elif num == 2:
        return True
    for i in range(2, (int)(num ** (0.5) + 1)):
        if (num % i == 0):
            return False
    return True

num = 151
checkPrime(num)

True

In [4]:
# 4. How to convert a list of tuples into a pandas DataFrame?

import pandas as pd
lis = [("A", 2,"B"), ("C", 5, "D"), ("E", 8, "G")]
dataFrame = pd.DataFrame(lis, columns = ['Name', 'Age', 'Job'])
print(dataFrame)

  Name  Age Job
0    A    2   B
1    C    5   D
2    E    8   G


In [5]:
# 5. Implement a function to find the factorial of a number recursively.

def fact(num):
    if (num == 1):
        return 1
    return num * fact(num - 1)

number = 5
fact(number)

120

In [6]:
# 6. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

# lis = [[1, 1, 1, 1, 1],
#        [1, 0, 0, 0, 1], 
#        [1, 1, 1, 1, 1]]
# arr = np.array(lis)
# print(arr)

arr = np.zeros((4, 5))
arr[:, 0] = 1
arr[0, :] = 1
arr[-1, :] = 1
arr[:, -1] = 1
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
# 7. Given a list of numbers, write a Python function to find 
# the sum of all the numbers in the list.

def allSum(list):
    sum = 0
    for ele in list:
        sum += ele
    return sum

list = [5, 2, 3, 4, 5]
print(allSum(list))

19


In [8]:
# 8. How to count the occurrences of each element in a NumPy array?

dict = {}
arr = np.array([1, 2, 1, 1, 1, 2, 5, 5, 8, 9, 9, 0, 1, 0, 1, 0])

for ele in arr:
    if ele in dict:
        dict[ele] += 1
    else:
        dict[ele] = 0    
print(dict)

{1: 5, 2: 1, 5: 1, 8: 0, 9: 1, 0: 2}


In [9]:
# 9. Write a Python function to check if a string is a palindrome.

def checkPalindrome(string):
    string = string.lower()
    if string == string[::-1]:
        return True
    return False

checkPalindrome("Nitin1")

False

In [10]:
# 10. Create a pandas DataFrame from a dictionary where each key-value pair represents a column.

dict = {"Name": ["A", 'B', 'C'], "Age": [1, 2, 3]}
df = pd.DataFrame(dict)
df.head()

Name  Age
0    A    1
1    B    2
2    C    3

In [11]:
# 11. Implement a function to check if two strings are anagrams of each other.

def checkAnagram(str1, str2):
    if len(str1) != len(str2):
        return False
    sortedStr1 = sorted(str1)
    sortedStr2 = sorted(str2)
    return sortedStr1 == sortedStr2

print(checkAnagram('angell', 'gglean'))

False


In [12]:
# 12. Write a Python function to find the maximum and minimum values in a list.

def maxMin(list):
    max = -1000
    min = 1000
    for ele in list:
        if ele > max:
            max = ele
        if ele < min:
            min = ele
    return max, min

print(maxMin([1, 2, 3, 4, 5]))

(5, 1)


In [13]:
# 13. Create a NumPy array with values ranging from 1 to 10.

arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
# 14. How to transpose a NumPy array?

lis = [[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1], 
       [1, 1, 1, 1, 1]]
arr = np.array(lis)
print(arr)
arr = np.transpose(arr)
print('\n',arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

 [[1 1 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]
 [1 1 1]]


In [15]:
# 15. Write a Python function to remove duplicates from a list.

def uniqueList(list):
    unique = []
    seen = set()
    for ele in list:
        if ele not in seen:
            unique.append(ele)
            seen.add(ele)
    return unique

print(uniqueList([1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2]))
        

[1, 2]


In [16]:
# 16. Implement a function to find the intersection of two lists.

def findIntersection(list1, list2):
    for i in range(len(list1)):
        for j in range(len(list2)):
            if list1[i] == list2[j]:
                return i, j
    return -1, -1

print(findIntersection([1, 2, 3], [4, 3, 3]))

(2, 1)


In [17]:
# 17. Write a NumPy program to compute the determinant of a given square array.
import numpy as np

def determinant(arr):
  # Check if the array is square
  if not arr.shape[0] == arr.shape[1]:
    raise ValueError("Input array must be a square matrix")

  # Use np.linalg.det for efficient determinant calculation
  return np.linalg.det(arr)

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
det = determinant(arr)
print(det)

6.66133814775094e-16


In [18]:
# 18. How to sort a pandas DataFrame by a specific column?

data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 22]}
df = pd.DataFrame(data)
df = df.sort_values(by = 'Age')
df.head()

Name  Age
2  Charlie   22
0    Alice   25
1      Bob   30

In [19]:
# 19. Create a Python function to generate the Fibonacci sequence up to n terms.

def fibo(n):
    first = 0
    next = 1
    res = []
    res.append(first)
    res.append(next)
    if n == 0:
        print("No output")
    elif n == 1:
        print(first)
    elif n == 2:
        print(res)
    j = 1
    for i in range(2, n):
        res.append(res[j] + res[j - 1])
        j += 1
    print(res)

fibo(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [20]:
# 20. Write a NumPy program to compute the inner product of two given vectors.

def product(vec1, vec2):
    return np.dot(vec1, vec2)

vec1 = np.array([1, 2, 3])
vec2 = np.array([3, 4, 5])
print(product(vec1, vec2))

26


In [21]:
# 21. Implement a function to flatten a nested list.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
arr = arr.reshape(-1)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [22]:
# 22. Write a Python function to check if a number is even or odd.

def checkEven(num):
    if (num % 2 == 0):
        return True
    return False

num = 6
if checkEven(num):
    print("Even")
else:
    print("Odd")

Even


In [23]:
# 23. How to rename columns in a pandas DataFrame?

data = {'col1': [1, 2, 3], 'col2': [4, 5, 6]}
df = pd.DataFrame(data)
newNames = {'col1': "Rem1", 'col2': 'Rem2'}
df = df.rename(columns = newNames)
print(df)

   Rem1  Rem2
0     1     4
1     2     5
2     3     6


In [24]:
# 24. Create a NumPy array of random integers between 1 and 100.

arr = np.random.randint(1, 101, size = 20)
print(arr)

[82 23 34 86 68 43 77 28 90 43 80 82 17 15 51 43 25 51 63 98]


In [25]:
# 25. Write a Python function to find the median of a list.

list = [1, 2, 3, 4, 5, 6, 10, 20]
arr = np.array(list)
print(np.median(arr))

4.5


In [26]:
# 26. Implement a function to rotate a list to the right by k steps.

def rotateRight(list, k):
    return list[k+1:] + list[0:k]
    
list = [1, 2, 3, 4, 5, 6, 10, 20]
print(rotateRight(list, 5))

[10, 20, 1, 2, 3, 4, 5]


In [27]:
# 27. Write a NumPy program to compute the mean, median, and mode of a given array.

import scipy as sp
arr = np.array(list)
mean = np.mean(arr)
median = np.median(arr)
mode = sp.stats.mode(arr)

print(mean, median, mode)

6.375 4.5 ModeResult(mode=1, count=1)


In [28]:
# 28. How to concatenate two pandas DataFrames?

data = {'col1': [1, 2, 3], 'col2': [4, 5, 6]}
df1 = pd.DataFrame(data)

data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 22]}
df2 = pd.DataFrame(data)

dfComb = pd.concat([df1, df2], axis = 1)
print(dfComb)

   col1  col2     Name  Age
0     1     4    Alice   25
1     2     5      Bob   30
2     3     6  Charlie   22


In [29]:
# 29. Create a Python function to generate all possible permutations of a list.

def permutations(data):
  # Base case: If the list is empty, yield an empty list (one permutation)
    if len(data) == 0:
        yield []
    else:
        # For each element in the list, generate permutations of the remaining elements
        for i, element in enumerate(data):
          # Get all permutations of the remaining elements (excluding the current element)
          for permutation in permutations(data[:i] + data[i + 1:]):
            # Prepend the current element to each permutation to create a new permutation
            yield [element] + permutation

# Example usage
data = [1, 2, 3]
for permutation in permutations(data):
    print(permutation)

[1, 2, 3]
[1, 3, 2]
[2, 1, 3]
[2, 3, 1]
[3, 1, 2]
[3, 2, 1]


In [30]:
# 30. Write a NumPy program to find the indices of 
# the maximum and minimum values along the given axis of an array.

def arg_extrema(arr, axis=None):
  # Find indices of maximum and minimum values
    max_indices = np.argmax(arr, axis=axis)
    min_indices = np.argmin(arr, axis=axis)

    return max_indices, min_indices

# Sample array
arr = np.array([[1, 5, 2], [4, 3, 6]])

# Find extrema along axis 0 (rows)
max_indices_row, min_indices_row = arg_extrema(arr, axis=0)
print("Maximum indices (rows):", max_indices_row)
print("Minimum indices (rows):", min_indices_row)

# Find extrema along axis 1 (columns)
max_indices_col, min_indices_col = arg_extrema(arr, axis=1)
print("Maximum indices (columns):", max_indices_col)
print("Minimum indices (columns):", min_indices_col)

# Find extrema across all elements (flattened array)
max_indices_flat, min_indices_flat = arg_extrema(arr)
print("Maximum indices (flattened):", max_indices_flat)
print("Minimum indices (flattened):", min_indices_flat)

Maximum indices (rows): [1 0 1]
Minimum indices (rows): [0 1 0]
Maximum indices (columns): [1 2]
Minimum indices (columns): [0 1]
Maximum indices (flattened): 5
Minimum indices (flattened): 0


In [31]:
# 31. Implement a function to check if a string contains only digits.

def checkDigit(str):
    check = "1234567890"
    for ele in str:
        if ele not in check:
            return False
    return True

print(checkDigit("123"))

True


In [32]:
# 32. Write a Python function to check if a given year is a leap year.

def checkYear(year):
    if (year % 100 == 0 & year % 400 == 0):
        return True
    elif (year % 4 == 0):
        return True
    return False

checkYear(2000)

True

In [33]:
# 33. How to drop missing values from a pandas DataFrame?

data = {'col1': [1, 2, 3], 'col2': [4, 5, None]}
df = pd.DataFrame(data)
dfNew = df.dropna()
print(dfNew)

   col1  col2
0     1   4.0
1     2   5.0


In [34]:
# 34. Create a NumPy array with random floats between 0 and 1.

arr = np.random.rand(10)
print(arr)

[0.57893934 0.31076535 0.85376836 0.285903   0.26176623 0.47183917
 0.04229393 0.79199267 0.46450759 0.56109144]


In [35]:
# 35. Write a Python function to calculate the power of a number using recursion.

def power(num, pow):
    if pow == 1:
        return num
    return num * power(num, pow-1)

print(power(2, 5))

32


In [36]:
# 36. Implement a function to calculate the factorial of a number using dynamic programming.

def factorial_dp(n):
  # Handle negative input (factorials are not defined for negative numbers)
    if n < 0:
        raise ValueError("Factorial is not defined for negative numbers")

    # Base case: factorial of 0 is 1
    dp = [1] * (n + 1)

  # Build the DP table iteratively
    for i in range(1, n + 1):
        dp[i] = dp[i - 1] * i

    return dp[n]

# Example usage
n = 5
result = factorial_dp(n)
print(f"The factorial of {n} is: {result}")

The factorial of 5 is: 120


In [37]:
# 37. Write a NumPy program to compute the outer product of two given vectors.

def product(vec1, vec2):
    return np.cross(vec1, vec2)

vec1 = np.array([1, 2, 3])
vec2 = np.array([3, 4, 5])
print(product(vec1, vec2))

[-2  4 -2]


In [38]:
# 38. How to convert a pandas DataFrame to a NumPy array?

data = {'col1': [1, 2, 3], 'col2': [4, 5, 100]}
df = pd.DataFrame(data)
df.head()

arr = df.to_numpy()
print(arr)

[[  1   4]
 [  2   5]
 [  3 100]]


In [43]:
# 39. Create a Python function to check if a given string is a valid email address.

def is_valid_email(email):
  # Check for basic structure: @ symbol separating username and domain
    if not '@' in email:
        return False

  # Split into username and domain parts
    username, domain = email.split('@')

  # Check if username and domain are non-empty strings
    if not username or not domain:
        return False

  # Basic check for allowed characters in username (alphanumeric and common symbols)
    allowed_username_chars = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-_")
    if not all(char in allowed_username_chars for char in username):
        return False

  # Basic check for dot (.) in domain
    if not '.' in domain:
        return False

  # Split domain into parts separated by dots
    domain_parts = domain.split('.')

  # Check if domain has at least two parts (e.g., example.com)
    if len(domain_parts) < 2:
        return False

  # Basic check for allowed characters in domain parts (alphanumeric and hyphens)
    allowed_domain_chars = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-")
    for part in domain_parts:
        if not all(char in allowed_domain_chars for char in part):
            return False

  # Basic checks passed, consider it potentially valid
    return True

# Example usage
emails = [
    "john.doe@example.com",  # Valid
    "invalid_email",          # Invalid (no @)
    "user@domain",            # Invalid (missing TLD)
    "user@domain.123",         # Potentially valid (numeric TLD allowed in some cases)
    "user.@domain.com",       # Invalid (missing username prefix)
    "user@domain-name.com",   # Valid
]

for email in emails:
    if is_valid_email(email):
        print(f"'{email}' appears to be valid (basic checks)")
    else:
        print(f"'{email}' appears to be invalid (basic checks)")


'john.doe@example.com' appears to be valid (basic checks)
'invalid_email' appears to be invalid (basic checks)
'user@domain' appears to be invalid (basic checks)
'user@domain.123' appears to be valid (basic checks)
'user.@domain.com' appears to be valid (basic checks)
'user@domain-name.com' appears to be valid (basic checks)


In [44]:
# 40. Write a NumPy program to compute the cross product of two given vectors.

def product(vec1, vec2):
    return np.cross(vec1, vec2)

vec1 = np.array([1, 2, 3])
vec2 = np.array([3, 4, 5])
print(product(vec1, vec2))

[-2  4 -2]


In [45]:
# 41. Implement a function to check if a list is sorted in ascending order.

def checkSorted(list):
    for i in range(1, len(list)):
        if list[i] < list[i-1]:
            return False
    return True

print(checkSorted([1, 2, 3, 4, 5, 9, 0, 1]))

False


In [68]:
# 42. Write a Python function to find the longest common prefix of a list of strings.

def longest_common_prefix(strs):
  # Handle empty list or list with one element
    if not strs:
        return ""

  # Initialize prefix as the first string
    prefix = strs[0]

  # Iterate through remaining strings, shortening the prefix if necessary
    for s in strs[1:]:
        while prefix != s[:len(prefix)]:
            prefix = prefix[:-1]
        if not prefix:
            return ""

    return prefix

# Example usage
strs = ["flower", "flow", "flight"]
longest_prefix = longest_common_prefix(strs)
print(longest_prefix)  # Output: "fl"

fl


In [70]:
# 43. How to drop duplicate rows from a pandas DataFrame?

data = {'col1': [1, 2, 2, 3, 1], 'col2': ['A', 'B', 'B', 'C', 'A']}
df = pd.DataFrame(data)
print(df)
dfNew = df.drop_duplicates()
print(dfNew)

   col1 col2
0     1    A
1     2    B
2     2    B
3     3    C
4     1    A
   col1 col2
0     1    A
1     2    B
3     3    C


In [46]:
# 44. Create a NumPy array with evenly spaced values between 1 and 10.

arr = np.arange(1, 11, 2)
print(arr)

[1 3 5 7 9]


In [71]:
# 45. Write a Python function to find the GCD (Greatest Common Divisor) of two numbers.

def gcd(num1, num2):
    if num1 < num2:
        num1, num2 = num2, num1
    while num2 != 0:
        r = num1 % num2
        if r == 0:
            return num2
        num1 = num2
        num2 = r

print(gcd(2, 5))

1


In [50]:
# 46. Implement a function to check if a string contains only vowels.

def checkVowels(str):
    vowels = "aeiou"
    str = str.lower()
    for ele in str:
        if ele not in vowels:
            return False
    return True

print(checkVowels("ae"))

True


In [72]:
# 47. Write a NumPy program to compute the eigenvalues and eigenvectors of a given square array.

import numpy as np

def eig(A):
  # Ensure the input is a square array
    if A.shape[0] != A.shape[1]:
        raise ValueError("Input array must be a square matrix")

  # Use NumPy's eig function to compute eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(A)

    return eigenvalues, eigenvectors

# Sample square array
A = np.array([[1, 2], [3, 4]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = eig(A)

# Print the results
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [57]:
# 48. How to group rows in a pandas DataFrame by a specific column?

dict = {"Name": ["A", 'B', 'C'], "Age": [2, 2, 3]}
df = pd.DataFrame(dict)
newDf = df.groupby('Age')
newDf.head()

Name  Age
0    A    2
1    B    2
2    C    3

In [69]:
# 49. Create a Python function to check if a given string is a valid IPv4 address.

def checkIPV4(add):
    valid = "123456789"
    if add.count('.') == 3:
        parts = add.split('.')
        for ele in parts:
            if len(ele) > 4:
                return False
            for num in ele:
                if num not in valid:
                    return False
        return True
    return False
    
print(checkIPV4('1.22.3.4'))

True


In [74]:
# 50. Write a NumPy program to compute the percentile of a given NumPy array.

import numpy as np

def percentile(arr, q):
  # Check for valid percentile value
    if q < 0 or q > 100:
        raise ValueError("Percentile must be between 0 and 100")

  # Sorted copy to avoid modifying the original array
    sorted_arr = np.sort(arr)

  # Calculate the index based on percentile
    index = int(np.floor(q / 100 * len(sorted_arr)))

  # Handle edge cases (0th and 100th percentiles)
    if q == 0:
        return sorted_arr[0]
    elif q == 100:
        return sorted_arr[-1]

  # Return the percentile value
    return sorted_arr[index]

# Sample array
arr = np.array([3, 1, 4, 2, 5])

# Compute percentiles
p25 = percentile(arr, 25)
p50 = percentile(arr, 50)
p75 = percentile(arr, 75)

print("25th percentile:", p25)
print("50th percentile (median):", p50)
print("75th percentile:", p75)

25th percentile: 2
50th percentile (median): 3
75th percentile: 4


In [75]:
x = lambda a, b, c: a + b + c
print(x(1, 2, 3))

6
